In [6]:
list = [1,2,3, 'a']

In [7]:
import numpy as np

In [8]:
arr = np.array(list)

In [9]:
print(list)

[1, 2, 3, 'a']


In [10]:
print(arr)

['1' '2' '3' 'a']


In [11]:
one = np.arange(7)

In [12]:
print(one)

[0 1 2 3 4 5 6]


In [13]:
two = np.arange(3, 9, 0.1)
print(two)

[3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7
 4.8 4.9 5.  5.1 5.2 5.3 5.4 5.5 5.6 5.7 5.8 5.9 6.  6.1 6.2 6.3 6.4 6.5
 6.6 6.7 6.8 6.9 7.  7.1 7.2 7.3 7.4 7.5 7.6 7.7 7.8 7.9 8.  8.1 8.2 8.3
 8.4 8.5 8.6 8.7 8.8 8.9]


In [14]:
three = np.zeros(7)
print(three)

[0. 0. 0. 0. 0. 0. 0.]


In [18]:
four = np.zeros([7,9])
print(four)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [19]:
five = np.ones(5)
print(five)

[1. 1. 1. 1. 1.]


In [23]:
six = np.twos(7)
print(six)

AttributeError: module 'numpy' has no attribute 'twos'

In [25]:
seven = np.linspace(0, 100, 15)
print(seven)

[  0.           7.14285714  14.28571429  21.42857143  28.57142857
  35.71428571  42.85714286  50.          57.14285714  64.28571429
  71.42857143  78.57142857  85.71428571  92.85714286 100.        ]


In [26]:
eight = np.eye(5)
print(eight)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [27]:
nine = np.random.rand(5)
print(nine)

[0.97179515 0.21740012 0.41884572 0.29703044 0.23253984]


In [28]:
ten = np.random.rand(5,5)
print(ten)

[[0.22744201 0.88111481 0.44418628 0.92382331 0.68823925]
 [0.08753695 0.25207796 0.66739988 0.54434453 0.22665628]
 [0.35468106 0.88309368 0.42624282 0.19673171 0.32247739]
 [0.42683342 0.43831029 0.06504735 0.43164836 0.24072638]
 [0.02110175 0.27881084 0.05139452 0.88276642 0.60212434]]


In [29]:
eleven = np.random.randn(5,5)
print(eleven)

[[ 1.12340161 -0.03043653 -0.40900516 -1.91646018 -0.20395804]
 [-0.23848659 -1.57006079 -0.2753798  -0.51215371 -0.24229372]
 [-1.54807455  1.92350098  0.71437893  1.88138859  0.99622807]
 [ 1.50064201  0.06270222  1.19166957  0.47543585 -0.34566812]
 [-0.83977593  0.68689447  1.43659791 -0.30973139 -1.11072765]]


In [30]:
twelve = np.random.randn(5)
print(twelve)

[-0.91579858 -0.20111131  1.11602146  0.03976564 -0.14624977]


In [31]:
thirteen = np.random.randint(1,100,10)
print(thirteen)

[67  1 52 63 91 53 59 16 74 70]


In [32]:
eleven.reshape(25)

array([ 1.12340161, -0.03043653, -0.40900516, -1.91646018, -0.20395804,
       -0.23848659, -1.57006079, -0.2753798 , -0.51215371, -0.24229372,
       -1.54807455,  1.92350098,  0.71437893,  1.88138859,  0.99622807,
        1.50064201,  0.06270222,  1.19166957,  0.47543585, -0.34566812,
       -0.83977593,  0.68689447,  1.43659791, -0.30973139, -1.11072765])

In [33]:
twelve.reshape(2,3)

ValueError: cannot reshape array of size 5 into shape (2,3)

In [34]:
seven.reshape(3,5)

array([[  0.        ,   7.14285714,  14.28571429,  21.42857143,
         28.57142857],
       [ 35.71428571,  42.85714286,  50.        ,  57.14285714,
         64.28571429],
       [ 71.42857143,  78.57142857,  85.71428571,  92.85714286,
        100.        ]])

In [35]:
seven.max()

100.0

In [36]:
seven.min()

0.0

In [37]:
print(seven)

[  0.           7.14285714  14.28571429  21.42857143  28.57142857
  35.71428571  42.85714286  50.          57.14285714  64.28571429
  71.42857143  78.57142857  85.71428571  92.85714286 100.        ]


In [38]:
seven.argmax()

14

In [39]:
seven.argmin()

0

In [41]:
seven.shape

(15,)

In [43]:
ten.shape

(5, 5)

In [45]:
fourteen = np.random.randint(1,1000, 120)
fifteen = fourteen.reshape(2,3,4,5)
print(fifteen)

[[[[864 970 515 767 493]
   [249 679 369 426 555]
   [614 491 278 543 852]
   [702 275 401 821 438]]

  [[237 728 261 302 991]
   [669  42 366 518 823]
   [597 949 395 570 992]
   [888 815 302 632 321]]

  [[762 389 693 620 519]
   [514 681 270 550 186]
   [744 580 362 877 803]
   [833 892 424 412 916]]]


 [[[867 842 207 645 798]
   [389 925 363 401 461]
   [996  22 239 872 809]
   [225 837 115 385 359]]

  [[481 195 621 672 962]
   [202 680 289 975 369]
   [893 417 873 309 104]
   [202 894 281 821 256]]

  [[715 549 254 585 833]
   [781 354 524 612 919]
   [941  43 822 703 782]
   [226 437 402 177 134]]]]


In [46]:
fifteen.shape

(2, 3, 4, 5)

In [47]:
fifteen.dtype

dtype('int32')

In [48]:
arr.dtype

dtype('<U11')

In [49]:
arr[2:]

array(['3', 'a'], dtype='<U11')

In [50]:
arr[0:4] = 100

In [51]:
print(arr)

['100' '100' '100' '100']


In [55]:
four[9:62] = 100

In [56]:
print(four)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [58]:
sixteen = thirteen[2:7]
print(sixteen)

[52 63 91 53 59]


In [59]:
sixteen[0:3] = 100
print(thirteen)

[ 67   1 100 100 100  53  59  16  74  70]


In [60]:
seventeen = thirteen.copy()
seventeen[:1] = 99
print(thirteen)

[ 67   1 100 100 100  53  59  16  74  70]


In [61]:
print(seventeen)

[ 99   1 100 100 100  53  59  16  74  70]


In [62]:
ten[4,1]

0.2788108391456148

In [63]:
ten[:4, 1:]

array([[0.88111481, 0.44418628, 0.92382331, 0.68823925],
       [0.25207796, 0.66739988, 0.54434453, 0.22665628],
       [0.88309368, 0.42624282, 0.19673171, 0.32247739],
       [0.43831029, 0.06504735, 0.43164836, 0.24072638]])

In [64]:
arr = np.arange(0,10)

In [65]:
bool_arr = arr>5
print(bool_arr)

[False False False False False False  True  True  True  True]


In [66]:
arr[bool_arr]

array([6, 7, 8, 9])

In [67]:
arr[arr>5]

array([6, 7, 8, 9])

In [68]:
arr_2d = np.arange(50).reshape(5,10)
print(arr_2d)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [69]:
arr2 = [3,4,2,21,1]

In [70]:
arr + arr2

ValueError: operands could not be broadcast together with shapes (10,) (5,) 

In [73]:
arr3 = np.random.randint(1,100,10)

In [74]:
arr3

array([88, 33, 19,  4, 67, 62,  3, 34, 46, 50])

In [75]:
print(arr + arr3)

[88 34 21  7 71 67  9 41 54 59]


In [76]:
print(arr * arr2)

ValueError: operands could not be broadcast together with shapes (10,) (5,) 

In [77]:
print(arr * arr3)

[  0  33  38  12 268 310  18 238 368 450]


In [78]:
print(arr+100)

[100 101 102 103 104 105 106 107 108 109]


In [84]:
arr4 = np.random.randfloat(1,100,10)
print(arr4)

AttributeError: module 'numpy.random' has no attribute 'randfloat'

In [86]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [87]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [89]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [90]:
np.log(arr)

C:\Users\oms\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [91]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [94]:
print(arr/arr3)

[0.         0.03030303 0.10526316 0.75       0.05970149 0.08064516
 2.         0.20588235 0.17391304 0.18      ]
