In [1]:
import numpy as np

In [8]:
a = np.random.randn(4,3)
print(a)

[[-1.39093525 -1.26726137 -1.58298788]
 [-0.15341242 -0.0979309  -0.18311386]
 [ 0.3435766   0.55435429 -1.04805423]
 [ 2.36411739 -0.20150314 -0.52862727]]


In [21]:
b = np.random.randn(3,3)
print(b)

[[ 1.04218271  0.58268466  0.50046427]
 [ 1.32147267  0.30545952  1.26814139]
 [ 2.40593377  1.60758444 -0.10010916]]


In [23]:
c=a+b
print(c)
print(c.shape)

ValueError: operands could not be broadcast together with shapes (4,3) (3,3) 